### ISSUE TITLE
No error if token does not provide permission to delete repo

### ISSUE THREAD

**Issue by waldyrious** [caub/github-clean-forks#2]
I tried this with a token containing only `read:user`; upon listing the repositories, a red cross (:x:) is shown next to each link, with the alt text "remove xxx/yyy". Clicking the cross prompts a dialog to appear with the message "delete xxx/yyy fork?". Clicking OK on that dialog indeed removes the entry from the list, but the repository does not actually get deleted on GitHub.

I suppose the `delete_repo` permission would be necessary for that functionality to work, but in any case there should be an error message telling the user that.

**Comment by caub** [comment]
Thanks for reporting, could you check or tell me chat is the response (status and body) in that case?
Then there just need to update https://github.com/caub/github-clean-forks/blob/master/index.js#L213 which indeed removes the repo from the list in any case

**Comment by waldyrious** [comment]
@caub sorry I didn't reply earlier. The code currently returns an error:

> index.js:214:40
> SyntaxError: missing ) in parenthetical

I tried putting the code through [jshint](http://jshint.com/) to hopefully locate potential errors, but even with the "Assume: New JavaScript features (ES6)" option activated, it seems to be choking on some code that I can't make sense of.

For example, "missing semicolon" in https://github.com/caub/github-clean-forks/blob/bd3f974afa19e0607231172fd6e7ff0bb7deed9e/index.js#L23 and https://github.com/caub/github-clean-forks/blob/bd3f974afa19e0607231172fd6e7ff0bb7deed9e/index.js#L34, which seems to suggest it's failing to correctly parse the structure of the code (or indeed there are syntax errors). Could you take a look?

**Comment by caub** [comment]
I don't hit problems at those points, what browser are you using?

you can make a PR to fix syntax if you want (use eslint instead of jshint)

EDIT oh wait I see it

**Comment by waldyrious** [comment]
I'm using Firefox 61.0, if that helps. Right now there's a different error:

> index.js:218:10
> SyntaxError: redeclaration of formal parameter r
> note: Previously declared at line 213, column 15

I'd be glad to send a PR with syntax fixes, but I am not really familiar with ES6 code to be sure what fixes are needed. Any pointers would be welcome :)

**Comment by caub** [comment]
Thanks, it's good again, I'd be glad if you can test the fail condition https://github.com/caub/github-clean-forks/blob/master/index.js#L214-L217 like mentioned in your initial comment

**Comment by waldyrious** [comment]
@caub confirmed, it works now :) Clicking the :x: shows the confirmation dialog and clicking OK then takes me to the starting screen, with the message

> error: Must have admin rights to Repository.

I think it would be more user-friendly to not show the :x: if the token doesn't have those permissions, or at least make it disabled, with the error message in a tooltip when the user hovers it. Would that be possible?

**Comment by caub** [comment]
@waldyrious good point, but I don't know how to fetch the permissions, it's maybe possible https://developer.github.com/v3/repos For now I just documented somewhere that the GitHub token should be created with that permission

**Comment by waldyrious** [comment]
Ok :) in any case the tool is already quite usable as it is!
