### ISSUE TITLE
Preserve section expansion state when deleting a fork

### ISSUE THREAD

**Issue by waldyrious** [caub/github-clean-forks#4]
Currently, if I collapse, say, section 0 ("no branch from you -> safely removable") and start working on the repositories of another section, when I click the :x: and delete one of the repositores, all sections become expanded again. I would expect them to retain the state (expanded/collapsed) they had before the repository deletion.

**Comment by waldyrious** [comment]
Thanks for the quick reaction! However, it looks like the :x: are not showing up at all :/ 

The console shows no errors; it only prints two numbers, `100` and `64`, from the code at: https://github.com/caub/github-clean-forks/blob/8439a5179c66791075c63ddab2b67b40440ac53b/index.js#L36

Any hints for debugging what the issue could be?

**Comment by caub** [comment]
can you printscreen? works for me

**Comment by waldyrious** [comment]
Huh. Must've been a cache issue... I just tested it again and the cross marks appear correctly. Sorry for the noise.

I can also confirm that the preserving of section expansion status is working as expected. Many thanks for the quick fix!
