### ISSUE TITLE
Username does not not persist across sessions

### ISSUE THREAD

**Issue by waldyrious** [caub/github-clean-forks#5]
Loading the page https://caub.github.io/github-clean-forks/ after having submitted the appropriate credentials once before, does reload the token value (from local storage, IIUC), but the username field remains empty. I'm using Firefox 61.0 if it matters.

Here's what I see:

![screenshot from 2018-07-10 23-25-52](https://user-images.githubusercontent.com/478237/42541071-d65e3b88-8498-11e8-83dc-4da9ab7d9768.png)

**Comment by caub** [comment]
I don't remember why I didn't save the username, probably because I was testing with multiple usernames, I think it's a good idea to save it now, I'll try to do it

there's also `#username` https://caub.github.io/github-clean-forks#waldyrious

I'm also switching to firefox more and more btw
